name: SpecialArmor
version: 1.6
main: me.specialarmor.SpecialArmorPlugin
api-version: '1.21'
commands:
  szett:
    description: "Megnyitja a saját referencia páncél menüdet."
    aliases: [customszett, plusszszett, plusszett]
  specadmin:
    description: "Az adminisztrátori GUI sablon szerkesztése."
    permission: specialarmor.admin
  setspecial:
    description: "Tárgy hozzárendelése egy speciális szetthez."
    permission: specialarmor.admin
  specialreload:
    description: "Konfiguráció újratöltése."
    permission: specialarmor.admin
permissions:
  specialarmor.admin:
    description: "Adminisztrátori jogok a SpecialArmor pluginhoz."
    default: op
