name: SpecialArmor
version: 1.5
main: me.specialarmor.SpecialArmorPlugin
api-version: '1.21'
commands:
  setspecial:
    description: "Tárgy szetthez rendelése"
    permission: specialarmor.admin
  specialreload:
    description: "Config újratöltése"
    permission: specialarmor.admin
permissions:
  specialarmor.admin:
    description: "Admin jog"
    default: op
